# Main configuration file

Theme = "Default"
ShowLineNumbers = true
Keymap = "Default"
Compiler = "fasm.exe"
Include = "Include"
Left = 200.0
Top = 200.0
Width = 500.0
Height = 350.0
WindowSate = 0
LeftPanelWidth = 150.0
BottomPanelHeight = 80.0